import type { Config } from "tailwindcss";

/** Color tokens from Stitch Projectbase 2 HTML exports and nordic_ledger/DESIGN.md. */
const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb786",
        outline: "#757781",
        "on-secondary-container": "#4e6873",
        "on-surface-variant": "#44464f",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cbe7f3",
        error: "#ba1a1a",
        "surface-dim": "#d9dadb",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#2f447b",
        "on-background": "#191c1d",
        "surface-tint": "#485c95",
        "primary-container": "#1a3167",
        "on-surface": "#191c1d",
        "on-primary-container": "#869bd7",
        "on-tertiary-fixed-variant": "#6d3910",
        "on-tertiary-fixed": "#311400",
        "surface-container-highest": "#e1e3e4",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed": "#dae2ff",
        primary: "#001b4f",
        "tertiary-container": "#552700",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#001849",
        "on-secondary-fixed-variant": "#304a54",
        "secondary-fixed": "#cbe7f3",
        background: "#f8f9fa",
        secondary: "#48626c",
        "outline-variant": "#c5c6d1",
        "secondary-fixed-dim": "#afcbd7",
        "on-secondary-fixed": "#021f27",
        "inverse-primary": "#b2c5ff",
        "on-error": "#ffffff",
        "surface-container": "#edeeef",
        "surface-bright": "#f8f9fa",
        tertiary: "#351600",
        "on-tertiary-container": "#d18c5c",
        "surface-variant": "#e1e3e4",
        surface: "#f8f9fa",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdcc6",
        "inverse-surface": "#2e3132",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "Inter", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "Inter", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
