import type { Config } from "tailwindcss";

/** Color tokens aligned with Stitch Projectbase HTML (`secondary-container` ≈ #cce8f4 / #cbe7f3). */
const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdea5",
        "tertiary-container": "#453000",
        "surface-container-high": "#f6e5e1",
        "secondary-fixed": "#cbe7f3",
        "surface-container-highest": "#f0dfdb",
        "inverse-surface": "#382e2c",
        "inverse-primary": "#b2c5ff",
        "tertiary-fixed-dim": "#e9c176",
        "surface-tint": "#485c95",
        "on-tertiary-fixed": "#261900",
        "primary-fixed": "#dae2ff",
        "on-surface-variant": "#44464f",
        "primary-container": "#1a3167",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#2f447b",
        background: "#fff8f6",
        "on-secondary-fixed": "#021f27",
        primary: "#001b4f",
        "on-error-container": "#93000a",
        outline: "#757781",
        surface: "#fff8f6",
        "on-tertiary-container": "#bb9751",
        "on-surface": "#221a17",
        error: "#ba1a1a",
        "primary-fixed-dim": "#b2c5ff",
        "error-container": "#ffdad6",
        tertiary: "#2a1c00",
        "secondary-container": "#cbe7f3",
        "secondary-fixed-dim": "#afcbd7",
        "surface-container-low": "#fff1ed",
        "surface-dim": "#e7d6d3",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-background": "#221a17",
        "inverse-on-surface": "#feede9",
        "on-primary-container": "#869bd7",
        "on-tertiary-fixed-variant": "#5d4201",
        "outline-variant": "#c5c6d1",
        "surface-bright": "#fff8f6",
        "surface-variant": "#f0dfdb",
        "surface-container": "#fbeae6",
        secondary: "#48626c",
        "on-secondary-container": "#4e6873",
        "on-secondary-fixed-variant": "#304a54",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001849",
        /** App shell — exact values from product spec */
        "app-sky": "#cce8f4",
        "app-sidebar": "#1a3167",
        "app-topbar-border": "#b8d4e8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "Manrope", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "Inter", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
